---
os: linux

language: shell

cache:
  directories:
  - $HOME/.m2/repository

before_install:
- python -m SimpleHTTPServer 8080 &

install:
- |
  case "$TRAVIS_OS_NAME" in
    (linux) mvn verify ;; # only do ut on linux
    (windows) PATH="$PATH:/c/opt/jdk8/bin" /c/ProgramData/chocolatey/lib/maven/apache-maven-3.6.2/bin/mvn verify -DskipTests ;;
    (*) mvn verify -DskipTests ;;
  esac
- find target -maxdepth 1 -name '*.jar' -a ! -name '*source*' | xargs -I {} cp {} target/maven-wrapper.jar
- cp mvnw mvnw.cmd target/
- mkdir -p target/.mvn/wrapper
- cp .mvn/wrapper/MavenWrapperDownloader.java target/.mvn/wrapper/
- sed -e '/^wrapperUrl=/d' .mvn/wrapper/maven-wrapper.properties >target/.mvn/wrapper/maven-wrapper.properties
- echo "wrapperUrl=http://localhost:8080/target/maven-wrapper.jar" >>target/.mvn/wrapper/maven-wrapper.properties
- mv .mvn .mvn.bak

before_script:
- pushd target
- set -o pipefail
- curl http://localhost:8080/pom.xml >/dev/null || sleep 3 || curl http://localhost:8080/pom.xml >/dev/null

after_script:
- popd
- mv .mvn.bak .mvn
- kill `jobs -p`

jobs:
  include:

  - name: "Test for Linux"
    stage: test
    os: linux
    language: java
    jdk: openjdk8
    services:
    - docker
    before_install:
    - python -m SimpleHTTPServer 8080 &
    - docker pull adoptopenjdk/openjdk8:alpine-slim
    script:
    - true =========== /bin/sh ===========
    - ./mvnw -version
    - diff maven-wrapper.jar .mvn/wrapper/maven-wrapper.jar
    - ./mvnw -version | grep 'Apache Maven'

    - true =========== bash ===========
    - rm -f .mvn/wrapper/*.jar
    - test ! -f .mvn/wrapper/maven-wrapper.jar
    - bash ./mvnw -version
    - diff maven-wrapper.jar .mvn/wrapper/maven-wrapper.jar
    - bash ./mvnw -version | grep 'Apache Maven'

    - true =========== bash posix mode ===========
    - rm -f .mvn/wrapper/*.jar
    - test ! -f .mvn/wrapper/maven-wrapper.jar
    - bash --posix ./mvnw -version
    - diff maven-wrapper.jar .mvn/wrapper/maven-wrapper.jar
    - bash --posix ./mvnw -version | grep 'Apache Maven'

    - true =========== dash ===========
    - rm -f .mvn/wrapper/*.jar
    - test ! -f .mvn/wrapper/maven-wrapper.jar
    - dash ./mvnw -version
    - diff maven-wrapper.jar .mvn/wrapper/maven-wrapper.jar
    - dash ./mvnw -version | grep 'Apache Maven'

    - true =========== busybox ===========
    - rm -f .mvn/wrapper/*.jar
    - test ! -f .mvn/wrapper/maven-wrapper.jar
    - docker run --rm -i --net=host -v `pwd`:/cwd -v ~/.m2/repository:/root/.m2/repository -w /cwd adoptopenjdk/openjdk8:alpine-slim ./mvnw -version
    - diff maven-wrapper.jar .mvn/wrapper/maven-wrapper.jar
    - docker run --rm -i --net=host -v `pwd`:/cwd -v ~/.m2/repository:/root/.m2/repository -w /cwd adoptopenjdk/openjdk8:alpine-slim ./mvnw -version | grep 'Apache Maven'

  - name: "Test for macOS"
    os: osx
    osx_image: xcode9.3 # for jdk 8
    language: java
    script:
    - true =========== /bin/sh ===========
    - ./mvnw -version
    - diff maven-wrapper.jar .mvn/wrapper/maven-wrapper.jar
    - ./mvnw -version | grep 'Apache Maven'

    - true =========== bash ===========
    - rm -f .mvn/wrapper/*.jar
    - test ! -f .mvn/wrapper/maven-wrapper.jar
    - bash ./mvnw -version
    - diff maven-wrapper.jar .mvn/wrapper/maven-wrapper.jar
    - bash ./mvnw -version | grep 'Apache Maven'

    - true =========== bash posix mode ===========
    - rm -f .mvn/wrapper/*.jar
    - test ! -f .mvn/wrapper/maven-wrapper.jar
    - bash --posix ./mvnw -version
    - diff maven-wrapper.jar .mvn/wrapper/maven-wrapper.jar
    - bash --posix ./mvnw -version | grep 'Apache Maven'

  - name: "Test for windows (MSYS/MINGW/CYGWIN/CMD)"
    os: windows
    cache:
      directories:
      - $HOME/.m2/repository
      - /c/opt/jdk8
      - /c/opt/cygwin
      - /c/ProgramData/chocolatey/lib/maven/apache-maven-3.6.2
    before_install:
    - python -m SimpleHTTPServer 8080 &
    - test -d /c/opt/jdk8/bin || choco install jdk8 -params 'installdir=c:\\opt\\jdk8' -y
    - test -d /c/opt/cygwin/bin || choco install cygwin -params '/InstallDir:c:\\opt\\cygwin' -y
    - test -d /c/ProgramData/chocolatey/lib/maven/apache-maven-3.6.2/bin || choco install maven --version 3.6.2 -y
    script:
    - echo ================================================
    - echo "subsystem - `uname -s`" | grep MSYS
    - rm -f .mvn/wrapper/*.jar
    - test ! -f .mvn/wrapper/maven-wrapper.jar
    - JAVA_HOME=/c/opt/jdk8 ./mvnw -version
    - diff maven-wrapper.jar .mvn/wrapper/maven-wrapper.jar
    - PATH="$PATH:/c/opt/jdk8/bin" ./mvnw -version | grep 'Apache Maven'

    - echo ================================================
    - /c/Program\ Files/Git/bin/sh.exe -c 'echo subsystem - `uname -s`' | grep MINGW
    - rm -f .mvn/wrapper/*.jar
    - test ! -f .mvn/wrapper/maven-wrapper.jar
    - JAVA_HOME=/c/opt/jdk8 /c/Program\ Files/Git/bin/sh.exe -c 'exec ./mvnw -version'
    - diff maven-wrapper.jar .mvn/wrapper/maven-wrapper.jar
    - /c/Program\ Files/Git/bin/sh.exe -c 'PATH="$PATH:/c/opt/jdk8/bin" exec ./mvnw -version' | grep 'Apache Maven'

    - echo ================================================
    - cmd.exe /c 'c:\opt\cygwin\bin\sh.exe -lc "echo subsystem - `uname -s`"' | grep CYGWIN
    - rm -f .mvn/wrapper/*.jar
    - test ! -f .mvn/wrapper/maven-wrapper.jar
    - cmd.exe /c "c:\opt\cygwin\bin\sh.exe -lc \"cd build/$TRAVIS_REPO_SLUG/target && JAVA_HOME=/cygdrive/c/opt/jdk8 exec ./mvnw -version\""
    - diff maven-wrapper.jar .mvn/wrapper/maven-wrapper.jar
    - cmd.exe /c 'c:\opt\cygwin\bin\sh.exe -lc "cd build/'$TRAVIS_REPO_SLUG'/target && PATH=\"$PATH:/cygdrive/c/opt/jdk8/bin\" exec ./mvnw -version"' | grep 'Apache Maven'

    - echo ================================================
    - echo "subsystem - cmd.exe"
    - rm -f .mvn/wrapper/*.jar
    - test ! -f .mvn/wrapper/maven-wrapper.jar
    - JAVA_HOME='c:\opt\jdk8' cmd.exe /c 'cd build\'${TRAVIS_REPO_SLUG//\//\\}'\target & mvnw -version'
    - diff maven-wrapper.jar .mvn/wrapper/maven-wrapper.jar
    - cmd.exe /c 'set "PATH=%PATH%;c:\opt\jdk8\bin"& cd build\'${TRAVIS_REPO_SLUG//\//\\}'\target & mvnw -version' | grep 'Apache Maven'
